### ISSUE TITLE
Add support to run the app under Java 1.7

### ISSUE THREAD

**Issue by iromli** [GluuFederation/message-consumer#5]
We need to run message-consumer under Java 1.7. One of the reason is Ubuntu 14.04 is shipped with Java 1.7 and message-consumer doesn't run in Ubuntu 14.04.

**Comment by nynymike** [comment]
I don't see a problem with this. We should create a user "activemq", make sure the service runs as this user, and set $JAVA_HOME appropriately. We can distribute OpenJDK 1.7 JRE as a folder if necessary.
